In [16]:
R = int(input("Enter the number of rows:"))
C = int(input("Enter the number of columns:"))
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
m1= np.array(entries).reshape(R, C)
print(m1)
print("------------------------------------------------------------")
R1 = int(input("Enter the number of rows:"))
C1 = int(input("Enter the number of columns:"))
print("Enter the entries in a single line (separated by space): ")
entries = list(map(int, input().split()))
m2 = np.array(entries).reshape(R1, C1)
print(m2)
print("------------------------------------------------------------")
m3=m1.dot(m2)
print("dot product is:")
print(m3)
print("------------------------------------------------------------")
m4=m1.transpose()
print("transpose of matrix1:")
print(m4)
m5=m2.transpose()
print("transpose of matrix2:")
print(m5)
print("------------------------------------------------------------")
m6=m1.trace()
print("trace of matrix1:")
print(m6)
m7=m2.trace()
print("trace of matrix2:")
print(m7)
print("------------------------------------------------------------")
rank1 = np.linalg.matrix_rank(m1)
print("Rank of the given Matrix1 is : ",rank1)
rank2 = np.linalg.matrix_rank(m2)
print("Rank of the given Matrix2 is : ",rank2)
print("------------------------------------------------------------")
det1 = np.linalg.det(m1)
print("Determinant of given matrix1:")
print(det1)
det2 = np.linalg.det(m2)
print("Determinant of given matrix2:")
print(det2)
print("------------------------------------------------------------")
print("inverse of given matrix1:")
print(np.linalg.inv(m1))
print("inverse of given matrix2:")
print(np.linalg.inv(m2))
print("------------------------------------------------------------")
w, v = np.linalg.eig(m1)
  
print("Printing the Eigen values of the given square array:\n",
      w)

print("Printing Right eigenvectors of the given square array:\n",
      v)
x, y = np.linalg.eig(m2)
  
print("Printing the Eigen values of the given square array:\n",
      x)

print("Printing Right eigenvectors of the given square array:\n",
      y)

import numpy as np
Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
1 2 3 4
[[1 2]
 [3 4]]
------------------------------------------------------------
Enter the number of rows:2
Enter the number of columns:2
Enter the entries in a single line (separated by space): 
3 4 5 6
[[3 4]
 [5 6]]
------------------------------------------------------------
dot product is:
[[13 16]
 [29 36]]
------------------------------------------------------------
transpose of matrix1:
[[1 3]
 [2 4]]
transpose of matrix2:
[[3 5]
 [4 6]]
------------------------------------------------------------
trace of matrix1:
5
trace of matrix2:
9
------------------------------------------------------------
Rank of the given Matrix1 is :  2
Rank of the given Matrix2 is :  2
------------------------------------------------------------
Determinant of given matrix1:
-2.0000000000000004
Determinant of given matrix2:
-1.9999999999999971
----------------------